POST http://localhost:3000/product
Content-Type: application/json

{
	"name": "Add your name in the body",
  "description": "fdgd", 
  "price": 233, 
  "type": "khll"
}

GET http://localhost:3000/product
Content-Type: application/json

